[windows]
target1 ansible_host=X.X.X.X
target2 ansible_host=X.X.X.X
target3 ansible_host=X.X.X.X

target4 ansible_host=X.X.X.X
target5 ansible_host=X.X.X.X

[windows:vars]
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_user=vagrant
ansible_password=vagrant
ansible_port=5985
ansible_winrm_server_cert_validation=ignore
